# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88a1d71637ca1bc81970f4652bd921f1e2083dc4dc2b5c2008b8176648113de1314061aaedf1c14515cf169d3a8e7b081678e0a04ee2ed2566b18ac98946878f

test:
  secret_key_base: 926037800db9aa9824d873956514ef70683caf677004699f1a793e0c39609edbc68c2b5c3d3026ea018ea892b2bce7a7bb9c6c819484859434dfd8c141995af4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
